OUTPUT_DIR: '/media/wuyang/scratch/model/SCAN_v2_models/local/evaluate_c2f'
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/vgg16_caffe-292e1171.pth' # Initialed by imagenet

  RPN_ONLY: True
  FCOS_ON: True
  DA_ON: True
  ATSS_ON: False

  MIDDLE_HEAD:
    CONDGRAPH_ON: True

# Basic  settings
    NUM_CONVS_IN: 2 # For numerical stability (VGG without BN)
    NUM_CONVS_OUT: 1
    CAT_ACT_MAP: True
    IN_NORM: 'GN'

# Prototype settings
    COSINE_UPDATE_ON: True
    PROTO_ITER: 3
    USE_RNN: 'RNN'  # 'GRU' 'LSTM'
    PROTO_WITH_BG: True
    COND_WITH_BIAS: False
    PROTO_CHANNEL: 256
    PROTO_MOMENTUM: 0.99

# SCAN_v2
    SUB_SAMPLING: 'condition' # center
    NUM_POS_POINTS_SOURCE: 100
    NUM_POS_POINTS_TARGET: 100
    WITH_SELF_TRAINING: True
    WITH_OT: True

    TARGET_SAMPLING_CFG: 'dbscan'
    DBSCAN_EPS: 3
    DBSCAN_THR: 0.25
#    DBSCAN_THR: 0.05
    CON_TG_CFG: 'KLdiv'

# loss settings
    NODE_LOSS_WEIGHT: 1.0
    ACT_LOSS_WEIGHT: 1.0
    OT_LOSS_WEIGHT: 2.0

  BACKBONE:
    CONV_BODY: "VGG-16-FPN-RETINANET"
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5

  FCOS:
    NUM_CONVS_REG: 4
    NUM_CONVS_CLS: 4
    NUM_CLASSES: 9
    INFERENCE_TH: 0.05    # pre_nms_thresh    (default=0.05)
    PRE_NMS_TOP_N: 1000   # pre_nms_top_n     (default=1000)
    NMS_TH: 0.6          # nms_thresh        (default=0.6)
    REG_CTR_ON: True

  ADV:
    CON_NUM_SHARED_CONV_P7: 4
    CON_NUM_SHARED_CONV_P6: 4
    CON_NUM_SHARED_CONV_P5: 4
    CON_NUM_SHARED_CONV_P4: 4
    CON_NUM_SHARED_CONV_P3: 4
    #
#    USE_DIS_GLOBAL: True
    USE_DIS_CON: True
    CON_WITH_GA: False

    CON_FUSUIN_CFG: 'concat' #'concat', 'mul_detached', 'mul'
    GA_DIS_LAMBDA: 0.1
    GRL_APPLIED_DOMAIN: 'both'

    USE_DIS_P7: True
    USE_DIS_P6: True
    USE_DIS_P5: True
    USE_DIS_P4: True
    USE_DIS_P3: True

    USE_DIS_P7_CON: True
    USE_DIS_P6_CON: True
    USE_DIS_P5_CON: True
    USE_DIS_P4_CON: True
    USE_DIS_P3_CON: True

    GRL_WEIGHT_P7: 0.02
    GRL_WEIGHT_P6: 0.02
    GRL_WEIGHT_P5: 0.02
    GRL_WEIGHT_P4: 0.02
    GRL_WEIGHT_P3: 0.02
TEST:
  DETECTIONS_PER_IMG: 100 # fpn_post_nms_top_n  (default=100)
#  'precision' 'common', 'light'
  MODE: 'common'
DATASETS:
  TRAIN_SOURCE: ("cityscapes_train_cocostyle", )
  TRAIN_TARGET: ("cityscapes_foggy_train_cocostyle", )
  TEST: ("cityscapes_foggy_val_cocostyle", )


INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32

SOLVER:
  VAL_ITER: 100
  ADAPT_VAL_ON: True
  INITIAL_AP50: 35
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 80000
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 80000
  #
  BACKBONE:
    BASE_LR: 0.0025
    STEPS: (60000, 80000)
    WARMUP_ITERS: 2000
    WARMUP_METHOD: "constant"
  MIDDLE_HEAD:
    BASE_LR: 0.0025
    STEPS: (60000, 80000)
    WARMUP_ITERS: 2000
    WARMUP_METHOD: "constant"
    PLABEL_TH: (0.5, 1.0)
  #
  FCOS:
    BASE_LR: 0.0025
    STEPS: (60000, 80000)
    WARMUP_ITERS: 2000
    WARMUP_METHOD: "constant"
  #
  DIS:
    BASE_LR: 0.0025
    STEPS: (60000, 80000)
    WARMUP_ITERS: 2000
    WARMUP_METHOD: "constant"
