MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/vgg16_caffe-292e1171.pth' # Initialed by pretrained weight
  #
  WEIGHT: "./model_GA.pth" # Initialed by GA pretrained weight (Optimizer and scheduler should not be loaded)
  #
  RPN_ONLY: True
  FCOS_ON: True
  DA_ON: True
  BACKBONE:
    CONV_BODY: "VGG-16-FPN-RETINANET"
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    NUM_CLASSES: 2
    INFERENCE_TH: 0.05    # pre_nms_thresh    (default=0.05)
    PRE_NMS_TOP_N: 1000   # pre_nms_top_n     (default=1000)
    NMS_TH: 0.6           # nms_thresh        (default=0.6)
  ADV:
    #
    USE_DIS_GLOBAL: True
    USE_DIS_CENTER_AWARE: True
    CENTER_AWARE_WEIGHT: 20
    CENTER_AWARE_TYPE: "ca_feature" # or "ca_loss"
    #
    GA_DIS_LAMBDA: 0.1
    CA_DIS_LAMBDA: 0.1
    GRL_APPLIED_DOMAIN: 'both'
    #
    USE_DIS_P7: True
    USE_DIS_P6: True
    USE_DIS_P5: True
    USE_DIS_P4: True
    USE_DIS_P3: True
    #
    DIS_P7_NUM_CONVS: 4
    DIS_P6_NUM_CONVS: 4
    DIS_P5_NUM_CONVS: 4
    DIS_P4_NUM_CONVS: 4
    DIS_P3_NUM_CONVS: 4
    #
    CA_DIS_P7_NUM_CONVS: 4
    CA_DIS_P6_NUM_CONVS: 4
    CA_DIS_P5_NUM_CONVS: 4
    CA_DIS_P4_NUM_CONVS: 4
    CA_DIS_P3_NUM_CONVS: 4
    #
    GRL_WEIGHT_P7: 0.01
    GRL_WEIGHT_P6: 0.01
    GRL_WEIGHT_P5: 0.01
    GRL_WEIGHT_P4: 0.01
    GRL_WEIGHT_P3: 0.01
    #
    CA_GRL_WEIGHT_P7: 0.02
    CA_GRL_WEIGHT_P6: 0.02
    CA_GRL_WEIGHT_P5: 0.02
    CA_GRL_WEIGHT_P4: 0.02
    CA_GRL_WEIGHT_P3: 0.02
TEST:
  DETECTIONS_PER_IMG: 100 # fpn_post_nms_top_n  (default=100)
DATASETS:
  TRAIN_SOURCE: ("kitti_train_caronly", ) 
  TRAIN_TARGET: ("cityscapes_train_caronly_cocostyle", )
  TEST: ("cityscapes_val_caronly_cocostyle", )
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 10000
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 250
  #
  BACKBONE:
    BASE_LR: 0.005
    STEPS: (120000, 160000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
  #
  FCOS:
    BASE_LR: 0.005
    STEPS: (120000, 160000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
  #
  DIS:
    BASE_LR: 0.005
    STEPS: (120000, 160000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"